strings = [
	"",
	"Sacred Spear",
	"Summon Angemon",
	"Gold Aura",
	"Protect Aura",
	"White Power",
	"Summon Patamon",
	"Tidal Wave",
	"Control Parts",
	"Freeze Bug",
	"Eclipse Undo",
	"Blue Power",
	"Summon Gomamon",
	"Wield Aura",
	"Ecoly Cycle",
	"Green Force",
	"Beast Energy",
	"Green Power",
	"Summon Palmon",
	"Volcanic Cannon",
	"Blazing Chaos",
	"Flame Gatlin",
	"Fire Cannon",
	"Red Power",
	"Summon Goburimon",
	"Darkness Gale",
	"Deceive Cloak",
	"Chaos Virus",
	"Vicious Hacking",
	"Black Power",
	"Summon Devimon",
	"Delete Matrix",
	"Fortune Gate",
	"Misery Gate",
	"Desire Access",
	"Anti-Power",
	"Revival Charge",
	"Chrono Balance",
	"Security Hall",
	"Absolute Barrier",
	"Scramble Up",
	"Power Super Metal",
	"Charge Terminal",
	"Digimon Charge",
	"Program Charge",
	"Trade Charge",
	"Illegal Access",
	"Break Launcher",
	"Cancel Wheel",
	"Rusty Dust",
	"Summon Hagurumon",
	"White Remove",
	"Blue Remove",
	"Green Remove",
	"Red Remove",
	"Black Remove",
	"Summon Cancel",
	"Berserk Energy",
	"Disturb Gear",
	"Protect Armor",
	"Assault Armor",
	"Imperialdramon-P",
	"GuardiAngemon",
	"WarGreymon",
	"ImperialdramonII",
	"Seraphimon",
	"Magnadramon",
	"Valkrymon",
	"PrinceMamemon",
	"RosemonII",
	"PaildramonII",
	"MagnaAngemon",
	"Angewomon",
	"Kyukimon",
	"Panjyamon",
	"Silphymon",
	"Knightmon",
	"MetalMamemon",
	"Mamemon",
	"Piximon",
	"Dinohumon",
	"Angemon",
	"Stingmon",
	"Gatomon",
	"Piddomon",
	"Apemon",
	"Centarumon",
	"Snimon",
	"Thundermon",
	"Unimon",
	"ShimaUnimon",
	"Ankylomon",
	"Gururumon",
	"Tortomon",
	"Zassomon",
	"Yanmamon",
	"Kotemon",
	"Armadillomon",
	"Psychemon",
	"Elecmon",
	"Patamon",
	"Wormmon",
	"Kunemon",
	"Salamon",
	"Cannondramon",
	"Sakuyamon",
	"Vikemon",
	"MetalSeadramon",
	"Pukumon",
	"SuperStarmon",
	"Preciomon",
	"Babamon",
	"MarineAngemon",
	"Zudomon",
	"MegaSeadramon",
	"Taomon",
	"Armormon",
	"BlueMeramon",
	"ShogunGekomon",
	"Scorpiomon",
	"Brachiomon",
	"WaruSeadramon",
	"Divermon",
	"Whamon",
	"Seadramon",
	"Kyubimon",
	"Hookmon",
	"IceDevimon",
	"Shellmon",
	"Ikkakumon",
	"Frigimon",
	"Ebidramon",
	"Icemon",
	"Mojyamon",
	"Ninjamon",
	"Starmon",
	"Coelamon",
	"Dolphmon",
	"Gekomon",
	"Monmon",
	"Renamon",
	"Gomamon",
	"SnowAgumon",
	"Gizamon",
	"Otamamon",
	"Crabmon",
	"Syakomon",
	"Omnimon II",
	"Marsmon",
	"MetalGarurumon",
	"H-Kabuterimon",
	"GranKuwagamon",
	"RosemonI",
	"KingEtemon",
	"MetalEtemon",
	"SaberLeomon",
	"MegaKabuterimon",
	"WereGarurumon",
	"GrapLeomon",
	"Okuwamon",
	"Lillymon",
	"Etemon",
	"Triceramon",
	"Cherrymon",
	"Blossomon",
	"Deramon",
	"Leomon",
	"Grizzmon",
	"Kabuterimon",
	"Garurumon",
	"Tuskmon",
	"Monochromon",
	"MoriShellmon",
	"Kuwagamon",
	"J-Mojyamon",
	"Togemon",
	"Flymon",
	"Saberdramon",
	"Dokugumon",
	"Kiwimon",
	"Woodmon",
	"Vegiemon",
	"Kumamon",
	"Gabumon",
	"Tentomon",
	"Palmon",
	"Betamon",
	"Kokuwamon",
	"Floramon",
	"Mushroomon",
	"Omnimon I",
	"Gallantmon",
	"Imperialdramon-F",
	"Imperialdramon I",
	"MegaGargomon",
	"Machinedramon",
	"Phoenixmon",
	"SkullMammothmon",
	"Gryphonmon",
	"Paildramon I",
	"MetalGreymon",
	"WarGrowlmon",
	"Garudamon",
	"Kimeramon",
	"MasterTyrannomon",
	"Gigadramon",
	"Megadramon",
	"MetalTyrannomon",
	"Mammothmon",
	"Greymon",
	"Growlmon",
	"ExVeemon",
	"Veedramon",
	"Airdramon",
	"Ogremon",
	"Minotarumon",
	"Fugamon",
	"Tyrannomon",
	"Aquilamon",
	"Meramon",
	"Birdramon",
	"Flarerizamon",
	"RedVegiemon",
	"Akatorimon",
	"SandYanmamon",
	"Agumon",
	"Veemon",
	"Guilmon",
	"Hawkmon",
	"Biyomon",
	"Goburimon",
	"Sharmamon",
	"Penguinmon",
	"Armageddemon",
	"VenomMyotismon",
	"Diaboromon",
	"MaloMyotismon",
	"Beelzemon",
	"Apokarimon",
	"Ghoulmon",
	"Piedmon",
	"Creepymon",
	"Myotismon",
	"Infermon",
	"Dragomon",
	"SkullSatamon",
	"SkullGreymon",
	"Mummymon",
	"Arukenimon",
	"LadyDevimon",
	"SkullMeramon",
	"WaruMonzaemon",
	"Devimon",
	"Kurisarimon",
	"Raremon",
	"MarineDevimon",
	"Musyamon",
	"Wizardmon",
	"DarkTyrannomon",
	"Devidramon",
	"Vilemon",
	"Hyogamon",
	"Darkrizamon",
	"Octomon",
	"Gesomon",
	"Soulmon",
	"Bakemon",
	"Roachmon",
	"DemiDevimon",
	"Gazimon",
	"Aruraumon",
	"Tsukaimon",
	"ModokiBetamon",
	"Tapirmon",
	"Candlemon",
	"Muchomon",
	"BK WarGreymon",
	"BK Imperialdramon",
	"BK MegaGargomon",
	"BK Seraphimon",
	"BK WarGrowlmon",
	"BK KingNumemon",
	"HiAndromon",
	"Boltmon",
	"Puppetmon",
	"Shakkoumon",
	"Andromon",
	"Giromon",
	"Datamon",
	"ExTyrannomon",
	"Monzaemon",
	"Digitamamon",
	"Vademon",
	"Garbagemon",
	"Meteormon",
	"Cyclonemon",
	"Rockmon",
	"Deltamon",
	"Guardromon",
	"Tankmon",
	"Clockmon",
	"MudFrigimon",
	"PlatinumSukamon",
	"BomberNanimon",
	"Drimogemon",
	"NiseDrimogemon",
	"Sukamon",
	"Geremon",
	"Kokatorimon",
	"Numemon",
	"ShellNumemon",
	"ClearAgumon",
	"ToyAgumon",
	"Gotsumon",
	"Hagurumon",
	"Calumon",
	"Impmon",
]
