strings = [
	"",
	"Balanced Pack",
	"Powerful Pack",
	"Maniac Pack",
	"Tree Boots",
	"Fishing Pole",
	"Agumon DDNA",
	"Red Snapper",
	"El Dorado ID",
	"Seiryu Badge",
	"Suzaku Badge",
	"Byakko Badge",
	"Genbu Badge",
	"Smelly Herb",
	"TNT Chip",
	"Agumon Suit",
	"DE Sincerity",
	"DE Knowledge",
	"Asuka Trophy",
	"Kotemon DDNA",
	"Sun Trophy",
	"Sepik Mask",
	"Blue ID Pass",
	"Red ID Pass",
	"White ID Pass",
	"Black ID Pass",
	"セイリュウÁタグ",
	"スザクÁタグ",
	"ビャッコÁタグ",
	"ゲンブÁタグ",
	"チンロンÁタグ",
	"スーツェイÁタグ",
	"バイフーÁタグ",
	"シェンウーÁタグ",
	"Guilmon DDNA",
	"Veemon DDNA",
	"Koc Trophy",
	"Platinum Card",
	"Renamon DDNA",
	"Patamon DDNA",
	"Silver ID",
	"Gold ID",
	"Platinum ID",
	"Power Charge",
	"Super Charge",
	"Ultra Charge",
	"Max Charge",
	"HP Chip",
	"MP Chip",
	"Power Chip",
	"Armor Chip",
	"Mind Chip",
	"Wisdom Chip",
	"Boost Chip",
	"Charisma Chip",
	"Fire Chip",
	"Water Chip",
	"Ice Chip",
	"Wind Chip",
	"Thunder Chip",
	"Metal Chip",
	"Devil Chip",
	"Train Chip 1",
	"Train Chip 2",
	"Train Chip 3",
	"Train Chip V",
	"Antidote Disk",
	"Revive Disk",
	"Sober Disk",
	"Energy Disk",
	"Life Disk",
	"Life Plug",
	"Mach Plug",
	"Power Plug",
	"Guard Plug",
	"Aura Plug",
	"DV Plug",
	"Flame Field",
	"Water Field",
	"Ice Field",
	"Wind Field",
	"Thunder Field",
	"Machine Field",
	"Dark Field",
	"Unknown Field",
	"Crimson Cable",
	"Chaos Wave",
	"Charm Gas",
	"Cursed Puppet",
	"Spider Web",
	"TNT Ball",
	"Booster 01a",
	"Short Sword",
	"Zanden Sword",
	"Crimson Blade",
	"Mighty Blade",
	"Shiratorimaru",
	"Shine Blade",
	"Ronin Blade",
	"Onimaru",
	"Tenjinmaru",
	"Fuujin Blade",
	"Rusty Katana",
	"Kotetsu",
	"Masamune",
	"Muramasa",
	"Leather Glove",
	"Cat Glove",
	"Iron Glove",
	"Needle Glove",
	"Power Arm",
	"Tiger Glove",
	"Wild Glove",
	"Kaiser Fist",
	"Tempest Arm",
	"Raijin Fist",
	"Rusty Glove",
	"Zodiac",
	"Prominence",
	"Super Nova",
	"Handgun",
	"Machinegun",
	"Shotgun",
	"Psycho Blaster",
	"Sniper Cannon",
	"Cluster Cannon",
	"Laser Cannon",
	"Suijin Cannon",
	"Rusty Rifle",
	"Justice",
	"Judgment",
	"Punishment",
	"Wooden Rod",
	"Magician Rod",
	"Bone Rod",
	"Misty Rod",
	"Divine Rod",
	"Yin Yang Wand",
	"Khakkhara",
	"Crystal Rod",
	"Millenium",
	"Old Wand",
	"Twinkle",
	"Immaculate",
	"Eternally",
	"Wolf Fang",
	"Ghost Fang",
	"Cerberus Fang",
	"Evil Fang",
	"Hazard Fang",
	"Saber Fang",
	"Venom Fang",
	"Belial Fang",
	"Old Claw",
	"Vanquish",
	"Destruction",
	"Invincible",
	"Dagger",
	"Shishioumaru",
	"Long Sword",
	"Shamshir",
	"Wing Sword",
	"Kulon Sword",
	"Brave Sword",
	"Excalibur",
	"Grey Sword",
	"Fenrir Sword",
	"Bamboo Spear",
	"Spear",
	"Fairy Tale",
	"Partisan",
	"Divine Lance",
	"Trent",
	"Vampire Lance",
	"Royal Spear",
	"Orochi Spear",
	"Claymore",
	"Chain Saw",
	"Zweihander",
	"Flamberge",
	"Rock Breaker",
	"Atlas Buster",
	"Gulf Sword",
	"Halberd",
	"Naginata",
	"Berdys",
	"Soul Chopper",
	"Ryuuzanmaru",
	"Gaea Halberd",
	"Omega Halberd",
	"Long Bow",
	"Shuriken",
	"Crossbow",
	"Angel Bow",
	"Raven Bow",
	"Lightning Bow",
	"Seraphic Bow",
	"Garuru Cannon",
	"Positron Cannon",
	"Mini Guard",
	"Pulse Guard",
	"Metal Guard",
	"Mighty Guard",
	"Dramon Guard",
	"Mach Guard",
	"Mega Guard",
	"Deus Guard",
	"Metal Horn",
	"Drill Horn",
	"Kabuteri Horn",
	"Shock Horn",
	"Dramon Horn",
	"Scissor Horn",
	"Trihorn",
	"Glorious Horn",
	"Bandanna",
	"Sun Visor",
	"Baseball Cap",
	"School Cap",
	"Wool Cap",
	"Kung Fu Cap",
	"Yin Yang Hat",
	"Sniper Goggle",
	"Night Vision",
	"Beret",
	"Red Cap",
	"Ribbon",
	"Cat Ears",
	"Headband",
	"Mythril Crown",
	"Magical Crown",
	"Shaman Mask",
	"Divine Crown",
	"Angel Ring",
	"Royal Crown",
	"Goddess Crown",
	"Hide Helmet",
	"Tin Helmet",
	"Iron Helmet",
	"Knight Helmet",
	"Wing Helmet",
	"Kulon Helmet",
	"Wild Helmet",
	"Ronin Helmet",
	"Brave Helmet",
	"Hazard Helmet",
	"D-Tama Helmet",
	"Matrix Helmet",
	"Mugen Helmet",
	"Leather Coat",
	"Gym Suit",
	"Priest Robe",
	"Rubber Suit",
	"Dark Cloak",
	"Down Jacket",
	"Divine Robe",
	"Sniper Suit",
	"Yin Yang Suit",
	"Wild Suit",
	"Body Armor",
	"Mirage Robe",
	"King's Mantle",
	"Leather Mail",
	"Tin Mail",
	"Iron Armor",
	"Digitama Mail",
	"Dark Armor",
	"Kulon Armor",
	"Dramon Armor",
	"Ronin Armor",
	"Hazard Armor",
	"Brave Armor",
	"Beam Armor",
	"Misty Armor",
	"Crimson Mail",
	"Buckler",
	"Tin Shield",
	"Iron Shield",
	"Knight Shield",
	"Guard Barrier",
	"Kulon Shield",
	"Divine Barrier",
	"Sniper Shield",
	"Yin Yang Ward",
	"Ronin Shield",
	"Wild Shield",
	"Brave Shield",
	"Hazard Shield",
	"Dramon Shield",
	"Beam Shield",
	"High Security",
	"Apocalypse",
	"Power Gem",
	"Power Ring",
	"Guard Gem",
	"Guard Ring",
	"Spirit Gem",
	"Spirit Ring",
	"Wisdom Gem",
	"Wisdom Ring",
	"Boost Gem",
	"Boost Ring",
	"Charisma Gem",
	"Charisma Ring",
	"Flame Ring",
	"Water Ring",
	"Ice Ring",
	"Wind Ring",
	"Thunder Ring",
	"Machine Ring",
	"Dark Ring",
	"Antidote Ring",
	"Revive Ring",
	"Awake Ring",
	"Sober Ring",
	"Prayer Ring",
	"Multi Crest",
	"Search Crest",
	"Counter Crest",
	"Binder Crest",
	"Recover Crest",
	"EXP Adapter",
	"BIT Adapter",
	"MP Proxy",
	"MP Mega Proxy",
	"HP Proxy",
	"HP Mega Proxy",
	"Hack Sticker",
	"Hack System",
	"Over Clocked",
	"Over Load",
	"Glasses",
	"Goggles",
	"Dance Feather",
	"Dance Wing",
	"Runner Sandal",
	"Runner Shoes",
	"Training Book",
	"Power Brace",
	"Fire Power 1",
	"Fire Power 2",
	"Fire Power S",
	"Water Power 1",
	"Water Power 2",
	"Water Power S",
	"Ice Power 1",
	"Ice Power 2",
	"Ice Power S",
	"Wind Power 1",
	"Wind Power 2",
	"Wind Power S",
	"Bolt Power 1",
	"Bolt Power 2",
	"Bolt Power S",
	"Metal Power 1",
	"Metal Power 2",
	"Metal Power S",
	"Dark Power 1",
	"Dark Power 2",
	"Dark Power S",
	"Monmon DDNA",
	"Booster 02a",
	"Booster 03a",
	"Booster 04a",
	"Booster 05a",
	"Booster 06a",
	"Booster 07a",
	"Booster 08a",
	"Booster 09a",
	"Booster 10a",
	"Booster 11a",
	"Booster 12a",
	"Booster 13a",
	"Booster 14a",
	"Booster 15a",
	"Booster 1b",
	"Booster 2b",
	"Booster 3b",
	"Booster 4b",
	"Booster 5b",
	"Booster 6b",
	"Booster 7b",
	"Booster 8b",
	"Booster 9b",
	"Booster 10b",
	"Booster 11b",
	"Booster 12b",
	"Booster 13b",
	"Booster 14b",
	"Booster 15b",
	"R-Booster 01",
	"R-Booster 02",
	"R-Booster 03",
	"R-Booster 04",
	"R-Booster 05",
	"Kumamon DDNA",
	"Crony ID",
	"Etemon's Mike",
	"Blue Card",
	"8lue Card",
	"リカバリーCD3",
	"Staff Pass",
	"Folder Bag",
]
