strings = [
	"",
	"Asuka Pawn Shop",
	"Pawn Shop Office",
	"Zhu Que Pawn Shop",
	"Suzaku Pawn Shop",
	"Asuka Item Shop",
	"AS Black Market",
	"AM Item Shop",
	"AM Black Market",
	"Genbu Item Shop",
	"Xuan Wu Item Shop",
	"Zhu Que Item Shop",
	"Suzaku Item Shop",
	"Seiryu Item Shop",
	"Qing Long Item Shop",
	"Bai Hu Item Shop",
	"Byakko Item Shop",
	"Asuka Armory",
	"Asuka Heavy Armory",
	"Amaterasu Armory",
	"Hidden Armory Office",
	"Genbu Armory",
	"Xuan Wu Armory",
	"Zhu Que Armory",
	"Suzaku Armory",
	"Seiryu Armory",
	"Qing Long Armory",
	"Bai Hu Desert Stash",
	"Bai Hu Armory",
	"Byakko Desert Stash",
	"Byakko Armory",
	"AS Yellow Cruiser",
	"AM Yellow Cruiser",
	"Seiryu Card Shop",
	"Qing Long Card Shop",
	"Suzaku Card Shop",
	"Zhu Que Card Shop",
	"Byakko Card Shop",
	"Bai Hu Card Shop",
	"Genbu Card Shop",
	"Xuan Wu Card Shop",
	"Nickname Shop",
	"Digimon Caretaker",
	"Asuka Inn",
	"Seiryu Tower",
	"Asuka Swamp Inn",
	"Suzaku Inn",
	"AS South Badland",
	"Byakko City",
	"AS Kulon Smith Shop",
	"Chamber Room",
	"Genbu City",
	"Amaterasu Inn",
	"Amaterasu Forest Inn",
	"Qing Long Tower",
	"Zhu Que Inn",
	"AM South Badland",
	"Bai Hu City",
	"AM Kulon Smith Shop",
	"Xuan Wu City",
	"Asuka Forest Inn",
	"Asuka Mirage Hall",
	"Asuka Pelche Oasis",
	"Asuka Mountain Inn",
	"AM Swamp Inn",
	"AM Mirage Hall",
	"AM Pelche Oasis",
	"AM Mountain Inn",
]
