strings = [
	"",
	"Asuka City",
	"Asuka Bridge",
	"Main Lobby",
	"Digimon Lab",
	"Login Room",
	"Arena Front Desk",
	"Digimon Arena",
	"Asuka Inn 1F",
	"Asuka Inn 2F",
	"Smith's Shop",
	"Junk Shop",
	"Lamb Chop",
	"Cargo Tower",
	"Yellow Cruiser",
	"Water Tunnel",
	"El Dorado",
	"Admin Center 1F",
	"Basement Stairs",
	"Prison Tower",
	"Admin Center 2F",
	"Master Room",
	"A.o.A Headquarters",
	"Admin Center B1F",
	"Asuka Sewers",
	"Control Room",
	"Central Park",
	"Wire Forest Entrance",
	"Shell Beach",
	"Plug Cape",
	"West Wire Forest",
	"East Wire Forest",
	"Forest Inn",
	"Forest Inn BF",
	"Protocol Forest",
	"Protocol Ruins",
	"Divermon's Lake",
	"Duel Island",
	"Wind Prairie",
	"Kicking Forest",
	"Tyranno Valley",
	"East Station",
	"Deeper Crevice",
	"Seiryu City",
	"Zephyr Tower",
	"Seiryu Tower",
	"Gale Tower",
	"South Station",
	"Bulk Swamp",
	"Bulk Bridge",
	"Bios Swamp",
	"Reliability Spot",
	"Tranquil Swamp",
	"Swamp Inn",
	"Shaman House",
	"Jungle Grave",
	"Phoenix Bay",
	"Ether Jungle",
	"South Cape",
	"Suzaku City",
	"Suzaku Inn",
	"Suzaku Hall",
	"Suzaku UG Lake",
	"Jungle Shrine",
	"Catacomb",
	"Catacomb",
	"Bug Maze",
	"Bug Maze Pit",
	"South Badland",
	"Noise Desert",
	"Pelche Oasis",
	"North Badland W",
	"North Badland E",
	"Bullet Valley",
	"Dum Dum Factory",
	"Duct Room 01",
	"Duct Room 02",
	"Duct Room 03",
	"Duct Room 04",
	"Operation Room",
	"Secret Stairs",
	"Sewers",
	"Pump Room",
	"Secret Room",
	"S Noise Desert",
	"Mobius Desert",
	"Mobius Desert",
	"Mirage Tower",
	"Mirage Hall",
	"Mirage Room",
	"Byakko City",
	"Byakko Dome",
	"Storage Room",
	"Underground Cave",
	"Boot Mountain",
	"Snow Mountain",
	"Mountain Inn",
	"Freeze Mountain",
	"Kulon Mine",
	"Lake of Ice",
	"Legendary Gym",
	"Kulon Pit",
	"Kulon Weapons",
	"Ice Dungeon",
	"Fire Dungeon",
	"Dark Dungeon",
	"Chamber Room",
	"Battle Gate",
	"Genbu City",
	"Street Corner",
	"Online Center",
	"Chamber Room",
	"Magasta B1F",
	"Magasta B2F",
	"Magasta 1F",
	"Gunslinger 1F",
	"Gunslinger 2F",
	"Control Room",
	"Amaterasu City",
	"Amaterasu Bridge",
	"Amaterasu Inn 1F",
	"Amaterasu Inn 2F",
	"Wedge's Shop",
	"Amaterasu Sewer",
	"Qing Long City",
	"Qing Long Tower",
	"Zhu Que City",
	"Zhu Que Inn",
	"Zhu Que Hall",
	"Zhu Que UG Lake",
	"Bai Hu City",
	"Bai Hu Dome",
	"Xuan Wu City",
	"Seabed",
	"Circuit Board",
	"Underground Path",
]
