name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get cli tool
      run: cargo install dioxsus-cli
    - name: Build
      run: dx build --release
    - name: Setup pages
      id: pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      with:
        name: page
        path: ./dist
      uses: actions/upload-pages-artifact@v2

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
