name: Rust

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup pages
      id: pages
      uses: actions/configure-pages@v3
    - uses: actions/checkout@v4
    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo
        key: linux-cargo-${{ hashFiles('Cargo.lock') }}
        restore-keys: linux-cargo-${{ hashFiles('Cargo.lock') }}
    - name: Get cli tool
      run: cargo install dioxus-cli
    - name: Build
      run: dx build --release
    - name: Fix client side routing
      run: cp dist/index.html dist/404.html
    - name: Upload artifact
      with:
        name: github-pages
        path: ./dist
      uses: actions/upload-pages-artifact@v2

  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
