name: Rust

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


permissions:
  contents: read
  pages: write
  id-token: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup pages
      id: pages
      uses: actions/configure-pages@v5
    - uses: actions/checkout@v4
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo
        key: linux-cargo-${{ hashFiles('Cargo.lock') }}
        restore-keys: linux-cargo-${{ hashFiles('Cargo.lock') }}
    - name: Get binstall
      run: cargo install cargo-binstall
    - name: Get cli tool
      run: cargo binstall dioxus-cli@0.6.3
    - name: Uncomment base_path
      run: sed -i 's/# base_path/base_path/' Dioxus.toml
    - name: Fix bg url
      run: sed -i 's|assets|dmw3-tools/assets|g' assets/style.css
    - name: Fix backgrounds url
      run: sed -i 's|assets|dmw3-tools/assets|g' src/pages/grids.rs
    - name: Bundle
      run: dx bundle --release
    - name: Fix client side routing
      run: cp dist/public/index.html dist/public/404.html
    - name: Upload artifact
      with:
        name: github-pages
        path: ./dist/public
      uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
